name: Batfish Analysis

on: workflow_dispatch

jobs:
  batfish-job:
    runs-on: ubuntu-latest
    container: 
      image: batfish/allinone
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Batfish
        run: |
          mkdir -p /tmp/batfish
          cp -r configs /tmp/batfish
          cd /tmp/batfish
          batfish -runmode snapshot -snapshotname mySnapshot -upload
          batfish -runmode analysis -snapshotname mySnapshot -question reachability
