name: Run Python Script with Batfish

on:
  workflow_dispatch:

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybatfish
        pip install pandas

    - name: Save Python dependencies
      run: |
        pip freeze > requirements.txt
      continue-on-error: true

    - name: Upload dependencies
      uses: actions/upload-artifact@v3
      with:
        name: dependencies
        path: requirements.txt

  run-batfish:
    runs-on: ubuntu-latest

    needs: setup-python

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download dependencies
      uses: actions/download-artifact@v3
      with:
        name: dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and run Batfish container
      run: |
        docker run -d --name batfish -p 9997:9997 -p 9996:9996 batfish/allinone

    - name: Wait for Batfish to be ready
      run: |
        until curl -s http://localhost:9996/v1/version; do sleep 5; done

    - name: Run script
      env:
        BF_SESSION_HOST: localhost
      run: python run_batfish_client.py

    - name: Stop Batfish container
      if: always()
      run: docker stop batfish && docker rm batfish
