name: Batfish Analysis

on: 
  workflow_dispatch:

jobs:
  batfish-job:
    runs-on: ubuntu-latest
    container: 
      image: batfish/batfish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Batfish
        run: |
          mkdir -p /tmp/batfish
          cp -r configs /tmp/batfish
          cd /tmp/batfish
          /opt/batfish/bin/batfish -runmode snapshot -snapshotname mySnapshot -upload
          /opt/batfish/bin/batfish -runmode analysis -snapshotname mySnapshot -question reachability
