name: Run Python Script with Batfish

on:
  workflow_dispatch:

jobs:
   batfish-job:
    runs-on: ubuntu-latest
    #container: 
      #image: batfish/allinone

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybatfish
        pip install pandas     

    #- name: Run script
     # env:
     #   BF_SESSION_HOST: localhost
     # run: python run_batfish_client.py
