name: Batfish Analysis

on: 
  workflow_dispatch:

jobs:
  batfish-job:
    runs-on: ubuntu-latest
    container: 
      image: batfish/allinone
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          mkdir -p /tmp/batfish
          cp -r configs /tmp/batfish
          cd /tmp/batfish

      - name: Run Batfish Snapshot
        run: |
          /usr/local/batfish/bin/batfish -runmode snapshot -snapshotname mySnapshot -upload

      - name: Run Batfish Analysis
        run: |
          /usr/local/batfish/bin/batfish -runmode analysis -snapshotname mySnapshot -question reachability
